[project]
name = "clean-sha256"
authors = ["Clean SHA256 Team"]
description = "A secure, privacy-focused wellness tracking smart contract using SHA256 for data integrity"
telemetry = false
requirements = []
[contracts.sha256-wellness]
path = "contracts/sha256-wellness.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
